export const pokemonTypes = [
    { name: "bug", color: "#7bcf00", src:"./src/assets/Types/bug.svg"},
    { name: "dark", color: "#5a566a", src:"./src/assets/Types/dark.svg"},
    { name: "dragon", color: "#0076ff", src:"./src/assets/Types/dragon.svg" },
    { name: "electric", color: "#ffde00", src:"./src/assets/Types/electric.svg" },
    { name: "fairy", color: "#ff76ff", src:"./src/assets/Types/fairy.svg" },
    { name: "fighting", color: "#ff215b", src:"./src/assets/Types/fighting.svg" },
    { name: "fire", color: "#ff9900", src:"./src/assets/Types/fire.svg" },
    { name: "flying", color: "#89bdff", src:"./src/assets/Types/flying.svg" },
    { name: "ghost", color: "#4e6aff", src:"./src/assets/Types/ghost.svg" },
    { name: "grass", color: "#1cd80e", src:"./src/assets/Types/grass.svg" },
    { name: "ground", color: "#ff6b0d", src:"./src/assets/Types/ground.svg" },
    { name: "ice", color: "#2ee4c6", src:"./src/assets/Types/ice.svg" },
    { name: "normal", color: "#9fa39d", src:"./src/assets/Types/normal.svg" },
    { name: "poison", color: "#f149ff", src:"./src/assets/Types/poison.svg" },
    { name: "psychic", color: "#ff6c64", src:"./src/assets/Types/psychic.svg" },
    { name: "rock", color: "#d8bc5a", src:"./src/assets/Types/rock.svg" },
    { name: "steel", color: "#23a1bd", src:"./src/assets/Types/steel.svg" },
    { name: "water", color: "#14a8ff", src:"./src/assets/Types/water.svg" },
  ];