export const pokemonTypes = [
    { name: "bug", color: "#7bcf00",icon:"./bug.svg" },
    { name: "dark", color: "#5a566a",icon:"./dark.svg" },
    { name: "dragon", color: "#0076ff",icon:"./dragon.svg"  },
    { name: "electric", color: "#ffde00",icon:"./electric.svg"  },
    { name: "fairy", color: "#ff76ff", icon:"./fairy.svg"  },
    { name: "fighting", color: "#ff215b",icon:"./fighting/svg"  },
    { name: "fire", color: "#ff9900",icon:"./fre.svg"  },
    { name: "flying", color: "#89bdff",icon:"./flying.svg"  },
    { name: "ghost", color: "#4e6aff",icon:"./ghost.svg"  },
    { name: "grass", color: "#1cd80e",icon:"./grass.svg"  },
    { name: "ground", color: "#ff6b0d",icon:"./ground.svg"  },
    { name: "ice", color: "#2ee4c6",icon:"./ice.svg"  },
    { name: "normal", color: "#9fa39d",icon:"./normal.svg"  },
    { name: "poison", color: "#f149ff",icon:"./poison.svg"  },
    { name: "psychic", color: "#ff6c64",icon:"./psychic.svg"  },
    { name: "rock", color: "#d8bc5a",icon:"./rock.svg"  },
    { name: "steel", color: "#23a1bd",icon:"./steel.svg"  },
    { name: "water", color: "#14a8ff",icon:"./water.svg"  },
  ];